path: C:\Users\LabAdmin\Documents\data\test\Test_after_flippingChannels\2026-08-12
study_names: ''
idxs: ''
signal_process:
  heterodyne: di-homodyne
  null_point: 2
  initial_samples: 50
  baseline_correction:
    enabled: true
    pos: C:/Users/LabAdmin/Documents/data/test/Test_after_fftfix/2026-08-12/Test_after_fftfix_2026-08-12_8.8_spot_100ns-baseline-POS-1.txt
    neg: C:/Users/LabAdmin/Documents/data/test/Test_after_fftfix/2026-08-12/Test_after_fftfix_2026-08-12_8.8_spot_100ns-baseline-NEG-1.txt
fft:
  signal_proportion: 0.5
  use_derivative: true
  analysis_type: psd
lorentzian:
  signal_proportion: 1.0
  frequency_bounds:
  - 0.01
  - 0.9
  dc_filter_range:
  - 0
  - 50000
  bimodal_fit: false
  use_skewed_super_lorentzian: false
tgs:
  grating_spacing: 8.704246
  signal_proportion: 1.0
  maxfev: 1000000
plot:
  signal_process: true
  fft_lorentzian: true
  tgs: true
  settings:
    num_points: 0
